// Tasks Module — Mock Data

export const TASK_SUMMARY = {
    total: 12,
    done: 1,
    overdue: 2,
    critical: 2,
    completePct: 8,
};

// priority: critical | high | medium | low
// status:   backlog | todo | inprogress | review | done
export const TASKS = [
    {
        id: 't1',
        title: 'Stage mic check & sound test',
        description: 'Full FOH sound check in Hall B including all stage positions, monitor mix, and delay lines.',
        priority: 'high',
        status: 'todo',
        assignee: 'Jackson Lee', assigneeInitials: 'JL',
        due: 'Apr 13', dueRaw: '2025-04-13',
        start: 'Apr 12', startRaw: '2025-04-12',
        progress: 0,
        tags: ['AV', 'Stage'],
        linkedForm: 'AV Brief',
        effort: '0h / 4h',
        checklist: [
            { id: 'c1', text: 'FOH console check', done: false },
            { id: 'c2', text: 'Stage monitors configured', done: false },
            { id: 'c3', text: 'Delay lines set', done: false },
            { id: 'c4', text: 'Mic positions confirmed', done: false },
        ],
        activityLog: [
            { user: 'Sofia Davis', initials: 'SD', action: 'created', note: 'Task created from AV Brief Stage C', time: 'Apr 1 · 10:00 AM' },
            { user: 'Jackson Lee', initials: 'JL', action: 'commented', note: 'Will need 4 crew for this — confirming with Vikram', time: 'Apr 3 · 3:30 PM' },
        ],
        isOverdue: false,
        ganttStart: 8, ganttWidth: 14,
    },
    {
        id: 't2',
        title: 'LED wall test & calibration',
        description: 'Full LED wall calibration for Stage B including brightness levels and pixel mapping.',
        priority: 'high',
        status: 'todo',
        assignee: 'Jackson Lee', assigneeInitials: 'JL',
        due: 'Apr 13', dueRaw: '2025-04-13',
        start: 'Apr 11', startRaw: '2025-04-11',
        progress: 20,
        tags: ['AV', 'LED'],
        linkedForm: 'Equipment Check',
        effort: '1h / 5h',
        checklist: [
            { id: 'c1', text: 'Brightness calibrated', done: true },
            { id: 'c2', text: 'Pixel mapping verified', done: false },
            { id: 'c3', text: 'Colour profile set', done: false },
            { id: 'c4', text: 'Backup panel ready', done: false },
        ],
        activityLog: [
            { user: 'Jackson Lee', initials: 'JL', action: 'created', note: 'Added to Event Build-Up checklist', time: 'Apr 2 · 09:15 AM' },
        ],
        isOverdue: false,
        ganttStart: 6, ganttWidth: 16,
    },
    {
        id: 't3',
        title: 'Catering brief — Stage 2 submission',
        description: 'Submit Stage 2 of the catering brief including headcount and dietary breakdowns.',
        priority: 'critical',
        status: 'todo',
        assignee: 'Jane Doe', assigneeInitials: 'JD',
        due: 'Apr 2', dueRaw: '2025-04-02',
        start: 'Mar 30', startRaw: '2025-03-30',
        progress: 25,
        tags: ['Catering', 'Vendor'],
        linkedForm: 'Catering Brief',
        effort: '1h / 4h',
        checklist: [
            { id: 'c1', text: 'Headcount confirmed', done: true },
            { id: 'c2', text: 'Dietary breakdown submitted', done: false },
            { id: 'c3', text: 'Vendor sign-off received', done: false },
            { id: 'c4', text: 'Invoice stage triggered', done: false },
        ],
        activityLog: [
            { user: 'Jane Doe', initials: 'JD', action: 'created', note: 'Stage 2 now unlocked from Catering Brief', time: 'Mar 30 · 11:00 AM' },
        ],
        isOverdue: true,
        ganttStart: 0, ganttWidth: 4,
    },
    {
        id: 't4',
        title: 'Floor plan approval — client sign-off',
        description: 'Get final floor plan signed off by client before load-in begins.',
        priority: 'medium',
        status: 'done',
        assignee: 'Sofia Davis', assigneeInitials: 'SD',
        due: 'Mar 25', dueRaw: '2025-03-25',
        start: 'Mar 22', startRaw: '2025-03-22',
        progress: 100,
        tags: ['Venue', 'Client'],
        linkedForm: null,
        effort: '2h / 2h',
        checklist: [
            { id: 'c1', text: 'Draft floor plan sent', done: true },
            { id: 'c2', text: 'Client revisions incorporated', done: true },
            { id: 'c3', text: 'Final version approved', done: true },
        ],
        activityLog: [
            { user: 'Sofia Davis', initials: 'SD', action: 'created', note: 'Floor plan sent to client', time: 'Mar 22 · 10:00 AM' },
            { user: 'Sofia Davis', initials: 'SD', action: 'completed', note: 'Client signed off — all good', time: 'Mar 25 · 02:30 PM' },
        ],
        isOverdue: false,
        ganttStart: 0, ganttWidth: 5,
    },
    {
        id: 't5',
        title: 'Badge design sign-off',
        description: 'Finalise badge artwork and get internal sign-off before sending to print vendor.',
        priority: 'high',
        status: 'inprogress',
        assignee: 'Priya Sharma', assigneeInitials: 'PS',
        due: 'Apr 10', dueRaw: '2025-04-10',
        start: 'Apr 1', startRaw: '2025-04-01',
        progress: 55,
        tags: ['Registration', 'Design'],
        linkedForm: null,
        effort: '3h / 6h',
        checklist: [
            { id: 'c1', text: 'Design draft v1 complete', done: true },
            { id: 'c2', text: 'Internal review done', done: true },
            { id: 'c3', text: 'Revisions applied', done: false },
            { id: 'c4', text: 'Print-ready file exported', done: false },
            { id: 'c5', text: 'Vendor briefed', done: false },
        ],
        activityLog: [
            { user: 'Priya Sharma', initials: 'PS', action: 'created', note: 'Started badge design process', time: 'Apr 1 · 09:00 AM' },
        ],
        isOverdue: false,
        ganttStart: 0, ganttWidth: 10,
    },
    {
        id: 't6',
        title: 'AV brief Stage C — vendor submission',
        description: 'Vendor to submit technical specs for Stage C of the AV Brief pipeline.',
        priority: 'critical',
        status: 'todo',
        assignee: 'Jane Doe', assigneeInitials: 'JD',
        due: 'Apr 5', dueRaw: '2025-04-05',
        start: 'Apr 1', startRaw: '2025-04-01',
        progress: 0,
        tags: ['AV', 'Vendor'],
        linkedForm: 'AV Brief',
        effort: '0h / 3h',
        checklist: [
            { id: 'c1', text: 'Technical specs document ready', done: false },
            { id: 'c2', text: 'Submitted via AV Brief form', done: false },
            { id: 'c3', text: 'Agency confirmation received', done: false },
            { id: 'c4', text: 'Stage D auto-unlocked', done: false },
        ],
        activityLog: [
            { user: 'Sofia Davis', initials: 'SD', action: 'created', note: 'Task created from AV Brief Stage C approval', time: 'Apr 1 · 10:00 AM' },
        ],
        isOverdue: true,
        ganttStart: 0, ganttWidth: 6,
    },
    {
        id: 't7',
        title: 'Load-in schedule confirmation',
        description: 'Confirm load-in time slots with all vendors and update the master schedule.',
        priority: 'high',
        status: 'todo',
        assignee: 'Vikram Patel', assigneeInitials: 'VP',
        due: 'Apr 12', dueRaw: '2025-04-12',
        start: 'Apr 9', startRaw: '2025-04-09',
        progress: 0,
        tags: ['Logistics', 'Vendors'],
        linkedForm: null,
        effort: '0h / 2h',
        checklist: [
            { id: 'c1', text: 'All vendor slots collected', done: false },
            { id: 'c2', text: 'Conflicts resolved', done: false },
            { id: 'c3', text: 'Master schedule updated', done: false },
        ],
        activityLog: [],
        isOverdue: false,
        ganttStart: 8, ganttWidth: 12,
    },
    {
        id: 't8',
        title: 'Run-of-show final draft',
        description: 'Complete and distribute the final run-of-show document to all department leads.',
        priority: 'high',
        status: 'inprogress',
        assignee: 'Sofia Davis', assigneeInitials: 'SD',
        due: 'Apr 8', dueRaw: '2025-04-08',
        start: 'Apr 3', startRaw: '2025-04-03',
        progress: 65,
        tags: ['Operations', 'Planning'],
        linkedForm: null,
        effort: '4h / 6h',
        checklist: [
            { id: 'c1', text: 'Stage A timeline locked', done: true },
            { id: 'c2', text: 'Stage B timeline locked', done: true },
            { id: 'c3', text: 'Speaker run order confirmed', done: true },
            { id: 'c4', text: 'Breaks and buffers added', done: false },
            { id: 'c5', text: 'Distributed to all leads', done: false },
        ],
        activityLog: [
            { user: 'Sofia Davis', initials: 'SD', action: 'created', note: 'Started ROS draft from last year template', time: 'Apr 3 · 09:00 AM' },
        ],
        isOverdue: false,
        ganttStart: 2, ganttWidth: 8,
    },
    {
        id: 't9',
        title: 'Rigging spec final approval',
        description: 'Get final approval on rigging specs before load-in crew mobilises.',
        priority: 'medium',
        status: 'review',
        assignee: 'Jackson Lee', assigneeInitials: 'JL',
        due: 'Apr 9', dueRaw: '2025-04-09',
        start: 'Apr 6', startRaw: '2025-04-06',
        progress: 75,
        tags: ['AV', 'Compliance'],
        linkedForm: 'Rigging Spec',
        effort: '3h / 4h',
        checklist: [
            { id: 'c1', text: 'Structural load calc received', done: true },
            { id: 'c2', text: 'Safety officer review done', done: true },
            { id: 'c3', text: 'Venue ops team sign-off', done: true },
            { id: 'c4', text: 'Final sign-off from PM', done: false },
        ],
        activityLog: [
            { user: 'Jackson Lee', initials: 'JL', action: 'created', note: 'Rigging spec submitted for final review', time: 'Apr 6 · 11:00 AM' },
        ],
        isOverdue: false,
        ganttStart: 4, ganttWidth: 10,
    },
    {
        id: 't10',
        title: 'Security brief preparation',
        description: 'Prepare and distribute the security brief to all vendor and venue security leads.',
        priority: 'medium',
        status: 'backlog',
        assignee: 'Jane Doe', assigneeInitials: 'JD',
        due: 'Apr 11', dueRaw: '2025-04-11',
        start: 'Apr 8', startRaw: '2025-04-08',
        progress: 0,
        tags: ['Security', 'Operations'],
        linkedForm: null,
        effort: '0h / 3h',
        checklist: [
            { id: 'c1', text: 'Security brief template updated', done: false },
            { id: 'c2', text: 'Zoning maps attached', done: false },
            { id: 'c3', text: 'Distributed to leads', done: false },
        ],
        activityLog: [],
        isOverdue: false,
        ganttStart: 6, ganttWidth: 12,
    },
    {
        id: 't11',
        title: 'Sponsor branding placement confirmation',
        description: 'Confirm sponsor branding placement with client and send mockup for sign-off.',
        priority: 'low',
        status: 'backlog',
        assignee: 'Meera Nair', assigneeInitials: 'MN',
        due: 'Apr 12', dueRaw: '2025-04-12',
        start: 'Apr 9', startRaw: '2025-04-09',
        progress: 0,
        tags: ['Branding', 'Sponsor'],
        linkedForm: null,
        effort: '0h / 2h',
        checklist: [],
        activityLog: [],
        isOverdue: false,
        ganttStart: 8, ganttWidth: 12,
    },
    {
        id: 't12',
        title: 'Post-event survey setup',
        description: 'Configure the post-event feedback survey and set up auto-distribution triggers.',
        priority: 'low',
        status: 'backlog',
        assignee: 'Priya Sharma', assigneeInitials: 'PS',
        due: 'Apr 13', dueRaw: '2025-04-13',
        start: 'Apr 10', startRaw: '2025-04-10',
        progress: 0,
        tags: ['Registration', 'Post-event'],
        linkedForm: null,
        effort: '0h / 2h',
        checklist: [],
        activityLog: [],
        isOverdue: false,
        ganttStart: 8, ganttWidth: 14,
    },
];

export const KANBAN_COLUMNS = [
    { id: 'backlog',    label: 'Backlog',     dot: '#94a3b8' },
    { id: 'todo',       label: 'To Do',       dot: '#64748b' },
    { id: 'inprogress', label: 'In Progress', dot: '#f59e0b' },
    { id: 'review',     label: 'Review',      dot: '#3b82f6' },
    { id: 'done',       label: 'Done',        dot: '#22c55e' },
];

export const ANALYTICS_STATUS = [
    { label: 'Backlog',     count: 3, color: '#94a3b8' },
    { label: 'To Do',       count: 5, color: '#64748b' },
    { label: 'In Progress', count: 2, color: '#f59e0b' },
    { label: 'Review',      count: 1, color: '#3b82f6' },
    { label: 'Done',        count: 1, color: '#22c55e' },
];

export const ANALYTICS_WORKLOAD = [
    { name: 'Jackson', assigned: 3, done: 1 },
    { name: 'Jane',    assigned: 3, done: 0 },
    { name: 'Sofia',   assigned: 2, done: 1 },
    { name: 'Priya',   assigned: 2, done: 0 },
    { name: 'Vikram',  assigned: 1, done: 0 },
    { name: 'Meera',   assigned: 1, done: 0 },
];

export const ANALYTICS_VELOCITY = [
    { week: 'Mar 17', count: 1 },
    { week: 'Mar 24', count: 2 },
    { week: 'Mar 31', count: 1.5 },
    { week: 'Apr 7',  count: 2 },
    { week: 'Apr 14', count: 0.5 },
];

export const ANALYTICS_BURNDOWN = [
    { date: 'Apr 1',  remaining: 12 },
    { date: 'Apr 4',  remaining: 11 },
    { date: 'Apr 6',  remaining: 10 },
    { date: 'Apr 8',  remaining: 9  },
    { date: 'Apr 10', remaining: 7  },
    { date: 'Apr 13', remaining: 5  },
    { date: 'Apr 15', remaining: 11 },
];

export const FORM_TO_TASK_LINKS = [
    { form: 'AV Brief Stage B',       trigger: 'Stage B approved → 2 tasks created', date: 'Apr 1', count: 2 },
    { form: 'Catering Brief Stage 1', trigger: 'Stage 1 submitted → 1 task created', date: 'Mar 30', count: 1 },
];

export const GANTT_DATES = ['A1', 'A4', 'A7', 'A10', 'A13', 'A16', 'A19', 'A22'];
export const GANTT_DATE_LABELS = ['Apr 1', 'Apr 4', 'Apr 7', 'Apr 10', 'Apr 13', 'Apr 16', 'Apr 19', 'Apr 22'];
export const GANTT_TODAY_COL = 5;
